git submodule add https://github.com/vim-scripts/c.vim.git  bundle/c.vim
git submodule add https://github.com/vim-scripts/genutils.git  bundle/genutils
git submodule add https://github.com/vim-scripts/lookupfile.git  bundle/lookupfile
git submodule add https://github.com/preservim/nerdcommenter.git  bundle/nerdcommenter
git submodule add https://github.com/preservim/nerdtree.git  bundle/nerdtree
git submodule add https://github.com/vim-scripts/OmniCppComplete.git  bundle/OmniCppComplete
git submodule add https://github.com/vim-scripts/python.vim.git  bundle/python.vim
git submodule add https://github.com/vim-scripts/rainbow_parentheses.vim.git  bundle/rainbow_parentheses.vim
git submodule add https://github.com/vim-scripts/repeat.vim.git  bundle/repeat.vim
git submodule add https://github.com/vim-scripts/SuperTab.git  bundle/SuperTab
git submodule add https://github.com/vim-scripts/surround.vim.git  bundle/surround.vim
git submodule add https://github.com/vim-scripts/Tabular.git  bundle/Tabular
git submodule add https://github.com/vim-scripts/Tagbar.git  bundle/Tagbar
git submodule add https://github.com/vim-scripts/YankRing.vim.git  bundle/YankRing.vim
git submodule add https://github.com/vim-scripts/buffergrep.git  bundle/buffergrep
git submodule add https://github.com/vim-scripts/taglist.vim.git  bundle/taglist.vim
git submodule add https://github.com/vim-scripts/winmanager.git  bundle/winmanager
git submodule add https://github.com/vim-scripts/ctags.vim.git  bundle/ctags.vim
